# Generated by Django 5.0.7 on 2024-07-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_remove_plantsdata_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantsdata',
            name='picture2',
            field=models.URLField(default='http://102.130.116.251:4001/-PRSm7UXVai/01.jpg'),
        ),
    ]
