# Generated by Django 5.0.7 on 2024-07-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plantsdata_picture2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantsdata',
            name='name',
            field=models.CharField(default='some plant', max_length=80),
        ),
    ]
