# Generated by Django 5.0.7 on 2024-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_plantsdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantsdata',
            name='picture2',
            field=models.URLField(),
        ),
    ]
